### ISSUE TITLE
Hardcoded options in score.py

### ISSUE THREAD

**Issue by msbentsen** [loosolab/jlu-bda-2020#16]
I am still seeing hardcoded options for genome and width in the score.py script:
https://github.com/loosolab/jlu-bda-2020/blob/1b5272387243e01fe4bfd2d0bf01460af1875d20/score.py#L95-L100

How are you planning on solving that? And **when**?

**Comment by nknoppik** [comment]
I was thinking about a parser (for example with argparse) for the command line or another idea was to integrate these variables into the gui. I will fix it until the next week.

Update:
Jasmin wanted to write a wrapper for that.

**Comment by msbentsen** [comment]
I am hearing a lot of "thinking" and "wanting" - and not so much "doing" ;-) It would be really good if you could write some code and push it (and preferably before Friday). It doesn't need to work perfectly, but writing it helps you to find any issues early on. 

Because even if @Jasmin-Walter is writing a wrapper, your script still needs to be able to be called with arguments, right?

**Comment by Jasmin-Walter** [comment]
All hardcoded options have been removed.
