### ISSUE TITLE
Clean up of scripts

### ISSUE THREAD

**Issue by msbentsen** [loosolab/jlu-bda-2020#17]
This entire block doesn't have a single comment... ouch, it is really hard to read and figure out what is going on :(
https://github.com/loosolab/jlu-bda-2020/blob/1b5272387243e01fe4bfd2d0bf01460af1875d20/parser.py#L13-L50

Part of the problem is also that the syntax keeps changing between space/no space in the paths:
https://github.com/loosolab/jlu-bda-2020/blob/1b5272387243e01fe4bfd2d0bf01460af1875d20/parser.py#L37-L38

This documented part is really good!
https://github.com/loosolab/jlu-bda-2020/blob/1b5272387243e01fe4bfd2d0bf01460af1875d20/parser.py#L6-L11

But you still need to comment throughout the code, and make some space within the code to separate the different steps. Since the functionality of the code is rather simple, it really needs to shine on readability!

**Comment by Jasmin-Walter** [comment]
I have commented the code and adjusted the syntax and formatting of the paths. The code should be readable now :)

**Comment by msbentsen** [comment]
Great - looks much better! I am closing this issue 👍
