### ISSUE TITLE
Input to activator/repressor prediction

### ISSUE THREAD

**Issue by msbentsen** [loosolab/jlu-bda-2020#18]
How are you planning on setting up input/output parameters in this script? Right now, I still see it being hardcoded:
https://github.com/loosolab/jlu-bda-2020/blob/1b5272387243e01fe4bfd2d0bf01460af1875d20/components_fit.py#L247-L249

Also, should `n_components = 15` always be hardcoded like that, or is it something that the user might play with to fine-tune the results? Please push your current work!

**Comment by JonnyCodewalker** [comment]
This code has been removed in the latest release. It was just used for internal testing.
