### ISSUE TITLE
Allow user to pick chromosomes for each genome

### ISSUE THREAD

**Issue by fctsfrmspc** [loosolab/jlu-bda-2020#21]
Since we're not supposed to hardcode the chromosomes of interest and since each genome has a different set of chromosomes, the user must be able to filter the chromosomes they want for each genome (e.g. chr1 and chr2 for hg19, chr1 for GRCh38).
`csv.r` (and possibly `export_from_csv.r`) have to check if the chromosomes given by the user are valid and therefore require a list of genomes, each containing a list of chromosomes.

**Comment by Jasmin-Walter** [comment]
There is no need anymore for a list of genomes and corresponding chromosomes because we are running the program for only one genome at a time. Regarding this one genome, the chromosomes submitted by the user are validated via tf_analyzer.
