### ISSUE TITLE
Example Case: parameter is not accepted.

### ISSUE THREAD

**Issue by rwiegan** [loosolab/jlu-bda-2020#30]
I tried the example case shown in the readme.

`python bin/tf_analyzer.py -g hg19 -b kidney -t AR -c chr1`

`usage: tf_analyzer.py [-h] [-g GENOME] [-b BIOSOURCE [BIOSOURCE ...]] [-t TF [TF ...]] [-c CHROMOSOME [CHROMOSOME ...]] [-w WIDTH] [-o [OUTPUT_PATH]]
                      [-cs [COMPONENT_SIZE]] [-r] [--visualize | --list_chromosomes | --list_downloaded_data]
tf_analyzer.py: error: argument -t/--tf: invalid choice: 'AR' (choose from 'aars', 'aatf', 'abcf1', 'aco1', 'adar', 'adnp2', 'aff1', 'aff4', 'aggf1', 'ago1', 'ago2', 'ago3', 'ahctf1', 'ahr', 'akap1', 'akap8', 'akap8l', 'all', ...`

Seems like the readme needs an update or there is a problem regarding the cases.

**Comment by fctsfrmspc** [comment]
That was an error on my side. Biosource, TF, genome and chromosome arguments must be written in lower case letters. This was adressed in 558f2a70c4fe22edbf4b08427056948d58b833ef
