### ISSUE TITLE
-c choices

### ISSUE THREAD

**Issue by rwiegan** [loosolab/jlu-bda-2020#31]
Adding some invalid input for parameter -c results in a list of valid options:

```
python bin/tf_analyzer.py -g hg19 -b kidney -t ar -c no_chr  
usage: tf_analyzer.py [-h] [-g GENOME] [-b BIOSOURCE [BIOSOURCE ...]] [-t TF [TF ...]] [-c CHROMOSOME [CHROMOSOME ...]] [-w WIDTH] [-o [OUTPUT_PATH]]
                      [-cs [COMPONENT_SIZE]] [-r] [--visualize | --list_chromosomes | --list_downloaded_data]
tf_analyzer.py: error: argument -c/--chromosome: invalid choice: 'no_chr' (choose from 'chr1', 'chr10', 'chr11', 'chr11_KI270721v1_random', 'chr12', 'chr13', 'chr14', 'chr14_GL000009v2_random', 'chr14_GL000194v1_random', 'chr14_GL000225v1_random', 'chr14_KI270722v1_random', 'chr14_KI270723v1_random', 'chr14_KI270724v1_random', 'chr14_KI270725v1_random', 'chr14_KI270726v1_random', 'chr15', 'chr15_KI270727v1_random', 'chr16', 'chr16_KI270728v1_random', 'chr17', 'chr17_GL000205v2_random', 'chr17_KI270729v1_random', 'chr17_KI270730v1_random', 'chr18', 'chr19', 'chr1_KI270706v1_random', 'chr1_KI270707v1_random', 'chr1_KI270708v1_random', 'chr1_KI270709v1_random', 'chr1_KI270710v1_random', 'chr1_KI270711v1_random', 'chr1_KI270712v1_random', 'chr1_KI270713v1_random', 'chr1_KI270714v1_random', 'chr2', 'chr20', 'chr21', 'chr22', 'chr22_KI270731v1_random', 'chr22_KI270732v1_random', 'chr22_KI270733v1_random', 'chr22_KI270734v1_random', 'chr22_KI270735v1_random', 'chr22_KI270736v1_random', 'chr22_KI270737v1_random', 'chr22_KI270738v1_random', 'chr22_KI270739v1_random', 'chr2_KI270715v1_random', 'chr2_KI270716v1_random', 'chr3', 'chr3_GL000221v1_random', 'chr4', 'chr4_GL000008v2_random', 'chr5', 'chr5_GL000208v1_random', 'chr6', 'chr7', 'chr8', 'chr9', 'chr9_KI270717v1_random', 'chr9_KI270718v1_random', 'chr9_KI270719v1_random', 'chr9_KI270720v1_random', 'chrEBV', 'chrM', 'chrUn_GL000195v1', 'chrUn_GL000213v1', 'chrUn_GL000214v1', 'chrUn_GL000216v2', 'chrUn_GL000218v1', 'chrUn_GL000219v1', ....
```
Most of those choices seem not to work with the current genome. Is this a merged list of the choices overall genomes?
The --list_chromosomes parameter already has the function of displaying the correct Chr. You could use this function instead of displaying this huge list.

**Comment by Jasmin-Walter** [comment]
I currently use the choices option of argparse to check if a passed chromosome is valid. The problem is that I don't know which genome the user chooses before parsing the args and therefore I have to include all possible chromosomes in choices. I can, however, outsource the validation of the chromosomes from argparse and write a separate function in which I then take the respective genome into account.

**Comment by rwiegan** [comment]
It is up to you. But for example, if an invalid biosource is given, the script prints such a huge list of available biosources. Noone is looking at that list.

**Comment by Jasmin-Walter** [comment]
The parameters for genome, biosource, tf and chromosome are now checked outside argparse.
For the chromosomes, only those belonging to the specified genome are output as possible arguments.
To limit the output of possible tfs and biosources, only a maximum of 30 are output. To make the output meaningful, regex are used to check whether the argument passed by the user occurs as a substring in valid arguments, which are then output as possibilities.
