### ISSUE TITLE
Download progress

### ISSUE THREAD

**Issue by hschult** [loosolab/jlu-bda-2020#36]
I started the pipeline with some parameters, it successfully created the linkage table and is currently downloading. Now that it downloaded for a while, I wonder how much longer it will take.
It would be really nice to see some sort of progress, like how many more downloads are in the queue or something similar.

**Comment by fctsfrmspc** [comment]
`export_from_csv.r` now generates messages each time it attempts to download something, showing the current position in the queue (and chunk if necessary) via 920b9dcf0473ec9103781c009a2c2b9589ff3cfa

**Comment by hschult** [comment]
Great! You know you can close an issue when you are done with it.
