### ISSUE TITLE
UnboundLocalError: local variable 'chromosomes' referenced before assignment

### ISSUE THREAD

**Issue by rwiegan** [loosolab/jlu-bda-2020#39]
DeepBlue is currently down. But I tried it anyway.
`python bin/tf_analyzer.py -g mm9 -b liver -t gata4 polr2a -c chr1`

results in:

```
You are currently offline. You can only analyse data you already downloaded.
Traceback (most recent call last):
  File "bin/tf_analyzer.py", line 237, in <module>
    main()
  File "bin/tf_analyzer.py", line 166, in main
    if chrom != 'all' and chrom not in chromosomes[args.genome]:
UnboundLocalError: local variable 'chromosomes' referenced before assignment
```
There seems to be a problem regarding the chromosomes variable when running in offline mode.

**Comment by Jasmin-Walter** [comment]
By the time the error occured, the offline mode was not fully developed yet. The offline mode was officially added with commit 15db5ef and the error was fixed.
