### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by hschult** [loosolab/jlu-bda-2020#42]
The regex module is not in your conda environment! Please make sure **all** dependencies are installed.

https://github.com/loosolab/jlu-bda-2020/blob/e0598d845d535dde5f648ac76c6315da5452884f/bin/tf_analyzer.py#L13

```
Traceback (most recent call last):
  File "/mnt/workspace/hschult/jlu-bda-2020/bin/tf_analyzer.py", line 13, in <module>
    import regex
ModuleNotFoundError: No module named 'regex'
```

**Comment by JonnyCodewalker** [comment]
The dependency has been added, a rebuild of the environment will be required if it wasn't manually installed.
