### ISSUE TITLE
Error when running pipeline in background

### ISSUE THREAD

**Issue by hschult** [loosolab/jlu-bda-2020#43]
Call: `python bin/tf_analyzer.py -g mm9 -b liver --redo_file_validation`

Error:
```
analyse_main.py: unpacking
unpacking: liver
analysing: ctcf
mode auto: number of components is evaluated (components_fit.py)
qt.qpa.xcb: could not connect to display localhost:12.0
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, minimal, minimalegl, offscreen, vnc, webgl, xcb.

Aborted
```

I suspect this error can be traced back to matplotlib not being able to create plots when the pipeline is running in the background.
Coincidently I had a similar problem recently which could be fixed with the solution provided [here](https://www.dkrz.de/up/help/faq/mistral/python-matplotlib-fails-with-qxcbconnection-could-not-connect-to-display).

**Comment by JonnyCodewalker** [comment]
This issue should be resolved since the plots generated by matplotlib are no longer displayed. Please reopen if the error still occurs.
